---
abstract: 'solve some of the Natas server-side security war games'
author:
  - 'Mike Doherty <doherty@cpan.org>'
build_requires:
  Capture::Tiny: 0
  Module::Build: 0.3601
  Test::More: 0.88
  Test::Script: 1.05
  blib: 0
configure_requires:
  File::ShareDir::Install: 0.03
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Natas
no_index:
  directory:
    - corpus
    - inc
    - examples
requires:
  Carp: 0
  Data::Dumper: 0
  Getopt::Long: 0
  HTTP::Tiny: 0.034
  URI: 0
  perl: v5.16.3
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/doherty/natas-walkthrough/issues
  repository: git://github.com/doherty/natas-walkthrough.git
version: 0.001
